name: Docker Image CI

on:
  push:
    branches: [ "push_dockerhub" ]
  pull_request:
    branches: [ "push_dockerhub" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: williamtrung
          password: dckr_pat_UCimcgRD99WRItUsuZEkJtMvElk
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: williamtrung/bird_training_center_client:latest
